package com.roam.backend.model;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * Hotspot represents a WiFi hotspot location managed by an edge device.
 * Each hotspot is associated with a physical Raspberry Pi that provides WiFi access.
 */
@Entity
@Table(name = "hotspots")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Hotspot {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Device ID: UUID generated by the edge device (Raspberry Pi).
     * This is NOT auto-generated by the database.
     */
    @Column(name = "device_id", nullable = false, unique = true, length = 36)
    private String deviceId;

    /**
     * Human-readable name for the hotspot location.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Optional icon URL for display in the mobile app.
     */
    @Column(name = "icon_url")
    private String iconUrl;

    /**
     * Latitude coordinate with 7 decimal precision (~1cm accuracy).
     */
    @Column(nullable = false, precision = 10, scale = 7)
    private BigDecimal latitude;

    /**
     * Longitude coordinate with 7 decimal precision (~1cm accuracy).
     */
    @Column(nullable = false, precision = 10, scale = 7)
    private BigDecimal longitude;

    /**
     * WiFi network SSID.
     */
    @Column(nullable = false)
    private String ssid;

    /**
     * WiFi password. Can be null for open networks.
     */
    @Column
    private String password;

    /**
     * Price per minute in cents. Default is 2 cents/min ($1.20/hour).
     */
    @Column(name = "price_per_minute_cents", nullable = false)
    @Builder.Default
    private Integer pricePerMinuteCents = 2;

    /**
     * Stripe Connected Account ID for the business owner.
     * Used for revenue splitting via Stripe Connect.
     */
    @Column(name = "stripe_account_id")
    private String stripeAccountId;

    /**
     * Whether the hotspot is active and available for connections.
     */
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = true;

    /**
     * Whether the edge device is currently online (based on heartbeat).
     */
    @Column(name = "is_online", nullable = false)
    @Builder.Default
    private Boolean isOnline = false;

    /**
     * Last heartbeat timestamp from the edge device.
     */
    @Column(name = "last_heartbeat_at")
    private Instant lastHeartbeatAt;

    @Column(name = "created_at")
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
        updatedAt = Instant.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = Instant.now();
    }

    /**
     * Calculate the total price for a given duration.
     * @param durationMinutes Duration in minutes
     * @return Total price in cents
     */
    public int calculatePriceCents(int durationMinutes) {
        return pricePerMinuteCents * durationMinutes;
    }
}
