package com.roam.backend.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.Instant;

/**
 * WifiSessionRecord represents a historical record of a WiFi session in the SQL database.
 * This is used for analytics and audit trails, separate from the Redis cache used for real-time validation.
 */
@Entity
@Table(name = "wifi_sessions")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class WifiSessionRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Associated transaction (payment) for this session.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "transaction_id")
    private Transaction transaction;

    /**
     * The hotspot this session is for.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hotspot_id", nullable = false)
    private Hotspot hotspot;

    /**
     * Session token (UUID) generated by the backend.
     */
    @Column(name = "session_token", nullable = false, unique = true, length = 36)
    private String sessionToken;

    /**
     * Duration of the session in minutes.
     */
    @Column(name = "duration_minutes", nullable = false)
    private Integer durationMinutes;

    /**
     * Session start time in milliseconds since Unix epoch.
     * Uses milliseconds for consistency with mobile app.
     */
    @Column(name = "started_at", nullable = false)
    private Long startedAt;

    /**
     * Session expiry time in milliseconds since Unix epoch.
     */
    @Column(name = "expires_at", nullable = false)
    private Long expiresAt;

    /**
     * Customer's mobile device ID (UUID).
     */
    @Column(name = "customer_device_id", nullable = false, length = 36)
    private String customerDeviceId;

    /**
     * Client IP address assigned by the edge device.
     */
    @Column(name = "client_ip", length = 45)
    private String clientIp;

    /**
     * Session status: active, expired, revoked.
     */
    @Column(nullable = false, length = 50)
    @Builder.Default
    private String status = STATUS_ACTIVE;

    @Column(name = "created_at")
    private Instant createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = Instant.now();
    }

    /**
     * Session status constants.
     */
    public static final String STATUS_ACTIVE = "active";
    public static final String STATUS_EXPIRED = "expired";
    public static final String STATUS_REVOKED = "revoked";

    /**
     * Check if the session is currently active (not expired by time).
     */
    public boolean isActive() {
        return STATUS_ACTIVE.equals(status) && System.currentTimeMillis() < expiresAt;
    }

    /**
     * Mark session as expired.
     */
    public void markExpired() {
        this.status = STATUS_EXPIRED;
    }

    /**
     * Mark session as revoked (manually ended).
     */
    public void markRevoked() {
        this.status = STATUS_REVOKED;
    }
}
